name: sstar
channels:
        - conda-forge
        - bioconda
dependencies:
        - bedtools
        - demes
        - numpy=1.22.3
        - pandas=1.4.1
        - pip=22.0.4
        - pybedtools
        - python=3.8
        - r-base=4.1.2
        - r-essentials=4.1
        - rpy2=3.4.5
        - samtools
        - scikit-allel=1.3.5
        - snakemake=7.1.1
        - pip:
                - sstar==1.1.0
