name: sstar
channels:
        - conda-forge
        - bioconda
dependencies:
        - python=3.8
        - pip=22.0.4
        - scikit-allel=1.3.5
        - pandas=1.4.1
        - snakemake=7.1.1
        - numpy=1.22.3
        - r-base=4.1.2
        - r-essentials=4.1
        - r-spatstat=2.3_3
        - rpy2=3.4.5
        - pip:
                - sstar==1.0.0
