name: sstar
channels:
        - conda-forge
        - bioconda
dependencies:
        - bedtools
        - codecov
        - demes
        - numpy
        - pandas
        - pip
        - pytest
        - pytest-cov
        - python=3.8
        - samtools
        - scikit-allel
        - scipy
        - snakemake
        - r-base=4.1.2
        - r-essentials=4.1
        - rpy2
        - pip:
                - sstar==1.1.1
