name: sstar
channels:
        - conda-forge
        - defaults
dependencies:
        - jinja2=3.0.0
        - mkdocstrings=0.17.0
        - mkdocs-material
        - pandas
        - pip
        - python=3.8
        - python-markdown-math
        - r-base
        - r-spatstat
        - rpy2
        - scikit-allel
        - pip:
                - sstar==1.1.0
