site_name: sstar
site_url: "https://sstar.readthedocs.io"
repo_url: "https://github.com/xin-huang/sstar"
edit_uri: ""
docs_dir: 'docs'
theme:
        name: "material"
        palette:
                primary: cyan
                accent: cyan
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - sstar
markdown_extensions:
  - extra
  - tables
  - fenced_code
  - admonition
  - codehilite
extra_javascript:
  - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'
nav:
- Home: 'index.md'
- User Guide: 
        - Overview: 'userguide/overview.md'
        - Calculate S* scores: 'userguide/score.md'
        - Calculate quanitles of expected S*: 'userguide/quantile.md'
        - Calculate significant S* score thresholds: 'userguide/threshold.md'
        - Calculate source match rates: 'userguide/matchrate.md'
        - Get candidate introgressed fragments: 'userguide/tract.md'
- Examples: 'examples.md'
- References: 'references.md'
- API:
        - cal_s_star: 'API/cal_s_star.md'
        - cal_pvalue: 'API/cal_match_rate.md'
        - cal_threshold: 'API/cal_threshold.md'
        - get_quantile: 'API/get_quantile.md'
        - get_tract: 'API/get_tract.md'
        - utils: 'API/utils.md'
