name: build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-18.04", "ubuntu-20.04"]
        python-version: ["3.8", "3.9"]
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file conda-env.yml --name base
    - name: Test with pytest
      run: |
        export R_LIBS=${CONDA_PREFIX}/lib/R/library
        pytest --cov=. --cov-report term-missing
    - name: upload coverage report to codecov
      uses: codecov/codecov-action@v3
      with:
          name: codecov-umbrella
          fail_ci_if_error: true
          env_vars: OS,PYTHON
